[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/tba-event-data"
  to = "/.netlify/functions/tba-event-data"
  status = 200

[[redirects]]
  from = "/api/google-sheet-data"
  to = "/.netlify/functions/google-sheet-data"
  status = 200

[[redirects]]
  from = "/api/google-sheet-sources"
  to = "/.netlify/functions/google-sheet-sources"
  status = 200
